Add custom action provider for direct PDF sharing via email
senaite/senaite.publisher pull request #132
Opened 2023-02-04 12:55 UTC by ramonski

## Description of the issue/feature this PR addresses

This PR adds a custom action provider based on https://github.com/senaite/senaite.impress/pull/131, that allows to send the generated PDF directly via Email:

<img width="1168" alt="" src="https://user-images.githubusercontent.com/713193/216768742-2fa1df2a-40ed-4e0a-9106-1ee2457a09d5.png">

The action button is not a

<img width="792" alt="" src="https://user-images.githubusercontent.com/713193/216768794-5484576d-0561-429c-b044-884f40415baa.png">
ctive by default and can be enabled in the IMPRESS controlpanel:

## Current behavior before PR

It is not possible to send a generated PDF directly w/o storing it first, e.g. for custom templates meant for receipt confirmation.

## Desired behavior after PR is merged

It is possible to send a generated PDF directly w/o storing it first, e.g. for custom templates meant for receipt confirmation.

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2023-02-06 11:34 UTC, xispa requested changes
Just minor things/questions regarding code. 

Regarding functionality, 
- would be possible to hide the model after the "Send" button is clicked. I feel users will keep pushing the button and multiple emails will be sent otherwise. Alternatively, display a message and disable the "Send" button
- I get a `TypeError: this is undefined` when I either click the "Email" or "Save" buttons now
- I feel we need to somehow make clear that whilst "Email" button transitions the sample to published status, the rest of actions don't. Maybe an impress setting?

2023-02-06 11:34 UTC, xispa commented on src/senaite/impress/actions/providers.py
> +                emails.append(email)
I think it would be simpler if emails was as `set` and do `emails.add(email)` instead of checking each time if the email is present in the list

2023-02-06 11:34 UTC, xispa commented on src/senaite/impress/actions/providers.py
> +                    emails.append(email)
Would be simpler if `emails` was a `set`:

```python
for contact in obj.getCCContact():
    if not contact:
        continue
    email = contact.getEmailAddress()
    emails.add(email)

cc_emails = obj.getCCEmails().split(",")
emails.update(cc_emails)
```

2023-02-06 11:34 UTC, xispa commented on src/senaite/impress/adapters.py
> +        self.available = False
Since in most cases, the "availability" of the action provider will depend on some logic, I think it would be better if available was a function instead of an attribute.  I feel the constructor should only be in charge to initialize the basics and not call internal functions if possible. What do you think?

2023-02-06 12:15 UTC, ramonski commented
> * would be possible to hide the model after the "Send" button is clicked. I feel users will keep pushing the button and multiple emails will be sent otherwise. Alternatively, display a message and disable the "Send" button

It is kept open to show the Status Message:

<img width="505" alt="SENAITE IMPRESS 2023-02-06 1 PM-02-59" src="https://user-images.githubusercontent.com/713193/216968432-7af67a16-e097-4a5a-8635-b3a13944c09d.png">

However, this was not displayed in FireFox and fixed here:
https://github.com/senaite/senaite.impress/blob/4be6c1a3b5901127ce08bd2a433bd8947892d33d/webpack/app/senaite.impress.coffee#L331-L334

But in general, closing the modal after submit can be configured in the action adapter with the attribute `close_after_submit`:

```python
class ICustomActionProvider(Interface):
    """Provide additional action buttons in report preview
    """
    available = Attribute(
        "Boolean to control if the action should be rendered")
    title = Attribute(
        "Action title that will be rendered for the button")
    text = Attribute(
        "Help text that should be displayed inside the button")
    name = Attribute(
        "Uniqe button name of the action")
    url = Attribute(
        "Form action or modal view URL")
    modal = Attribute(
        "Boolean to control if the action should open a new modal")
    close_after_submit = Attribute(
        "Boolean to control if the modal should be closed after submit")
    css_class = Attribute(
        "CSS class of the action button")

    def get_action_data():
        """Returns the known attributes to the ReactJS component
        """
```

2023-02-06 12:30 UTC, ramonski commented
> * I get a `TypeError: this is undefined` when I either click the "Email" or "Save" buttons now

Should be fixed in https://github.com/senaite/senaite.impress/pull/132/commits/6e556d2dd046e62c1f08d430901ef3f05b3512fb

2023-02-06 12:35 UTC, ramonski commented
> Just minor things/questions regarding code.
> 
> Regarding functionality,
> 
> * would be possible to hide the model after the "Send" button is clicked. I feel users will keep pushing the button and multiple emails will be sent otherwise. Alternatively, display a message and disable the "Send" button
> * I get a `TypeError: this is undefined` when I either click the "Email" or "Save" buttons now
> * I feel we need to somehow make clear that whilst "Email" button transitions the sample to published status, the rest of actions don't. Maybe an impress setting?

I thought so as well. What do you think about the following approach:

- We remove the `Save` and the `Email` button and make it just `Store` which defaults to the Email View. In the setting we have a configuration which allows to disable the default redirect to the Email view, so that you end up with the behavior we have with "Save" at the moment

2023-02-06 12:43 UTC, ramonski commented on src/senaite/impress/actions/providers.py
> +                emails.append(email)
I wanted to maintain the order, therefore I chose this approach

2023-02-06 12:44 UTC, ramonski commented on src/senaite/impress/actions/providers.py
> +                    emails.append(email)
Here as well. Sometimes the order matters also in emails  😄

2023-02-06 12:45 UTC, ramonski commented on src/senaite/impress/adapters.py
> +        self.available = False
Yes, good point. I'll change it (also in the interface description)

2023-02-06 12:49 UTC, ramonski commented on src/senaite/impress/adapters.py
> +        self.available = False
Implemented here: https://github.com/senaite/senaite.impress/pull/132/commits/2e45c0ebc7fa827835a06bf7316b544d47250bb8

2023-02-07 09:17 UTC, xispa commented
> > * I feel we need to somehow make clear that whilst "Email" button transitions the sample to published status, the rest of actions don't. Maybe an impress setting?
> 
> I thought so as well. What do you think about the following approach:
> 
>     * We remove the `Save` and the `Email` button and make it just `Store` which defaults to the Email View. In the setting we have a configuration which allows to disable the default redirect to the Email view, so that you end up with the behavior we have with "Save" at the moment

Not sure, it might be confusing. Even if user wants the system to behave as it does with `Email` button most of the time is still useful to have the `Save` button as is. Maybe the solution is to make the actions and button texts to be more explicit:

- **Download**: downloads the generated PDF
- **Save**: saves the generated PDF
- **Share**: shares the generated PDF (now by email but maybe through another channel in future via modal)
- **Publish**: saves the generated PDF and publishes the sample
- **Share and publish**: saves, shares the generated PDF and publishes the sample

We could even be less confusing by removing *Share and publish* and simply prompt the user with a confirmation panel like *"Do you want to share the results report"* [Yes/No] when the "Publish" button is clicked. If user clicks to *Yes*, system redirects to the email view we have. Otherwise, saves the report and transitions the sample. So this would then look as follows:

- **Download**: downloads the generated PDF
- **Save**: saves the generated PDF
- **Share**: shares the generated PDF (now by email but maybe through another channel in future via modal)
- **Publish**: saves the generated PDF, publishes the sample and prompts the user to share the results report

However, to be coherent I think we should then rename the transition "Publish" by "Results report preview" or something alike. So the user would see an action with this name that clearly states that it will be redirected to the results report preview, from where one would be able to do several actions, but not necessarily publish.

2023-02-07 09:23 UTC, ramonski commented
Thanks for your input!
However, we would need then to change the "Publish" behavior, because the samples are not published directly after the report is created. This first happens after the Email was sent, or the user clicked on a PDF report and clicks again the (Force-)"Publish" Button.
Let's do this in another PR, there are some more in the queue on my side...

2023-02-07 09:24 UTC, xispa commented
> Thanks for your input! However, we would need then to change the "Publish" behavior, because the samples are not published directly after the report is created. This first happens after the Email was sent, or the user clicked on a PDF report and clicks again the (Force-)"Publish" Button. Let's do this in another PR, there are some more in the queue on my side...

:+1:

2023-02-07 09:24 UTC, xispa approved these changes
Excellent and exciting, keep pushing!

2023-02-07 09:25 UTC, merged