Refactored publish view controls and content table to viewlets
senaite/senaite.publisher pull request #133
Opened 2023-02-07 19:21 UTC by ramonski

## Description of the issue/feature this PR addresses

This PR refactors the setup-button, language selector and content listing of the publish view into separate viewlets.

## Current behavior before PR

All elements inside the publish view template

## Desired behavior after PR is merged

Elements are rendered by viewlets

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2023-02-07 21:31 UTC, xispa requested changes
I was not able to do functional testing. Did you missed to add the module `senaite.impress.browser.publish` maybe?

2023-02-07 21:31 UTC, xispa commented on src/senaite/impress/browser/viewlets/content.py
> +    """Viewlet that is displayed when the Auditlog is disabled
Should be something like "Viewlet that is displayed in the publish view above the publish controls"

2023-02-07 21:31 UTC, xispa commented on src/senaite/impress/browser/viewlets/configure.zcml
> +      layer="senaite.impress.interfaces.ILayer"
Why you rely on `ILayer` instead of `ISenaiteImpressLayer`? Also, why to not remove the former and leave only the latter in `interfaces.py`?

2023-02-07 21:31 UTC, xispa commented on src/senaite/impress/browser/viewlets/templates/content.pt
> +              i18n:domain="bika"
These `i18n` directives can be removed, span contents won't be translated

2023-02-07 21:31 UTC, xispa commented on src/senaite/impress/browser/configure.zcml
> +  <include package=".publish" />
```
ValidationError: ImportError: Module senaite.impress.browser has no global publish
```

2023-02-08 09:58 UTC, ramonski commented on src/senaite/impress/browser/viewlets/content.py
> +    """Viewlet that is displayed when the Auditlog is disabled
Apologies, I splitted the PR in 2 parts and forgot to remove some parts that should come next (replacement of the listing table to use `senaite.app.listing`). Removed in https://github.com/senaite/senaite.impress/pull/133/commits/3183a55c74748f35057161676a92e76e380c41a6

I also fixed the docstring in https://github.com/senaite/senaite.impress/pull/133/commits/99f1d6d4405fecf247bb4faed78029e418cdbf0b

2023-02-08 10:00 UTC, ramonski commented on src/senaite/impress/browser/viewlets/configure.zcml
> +      layer="senaite.impress.interfaces.ILayer"
Good point, I changed that in https://github.com/senaite/senaite.impress/pull/133/commits/e109cb01e0068d058dd0a1c3084bd68b193a3ab5

2023-02-08 10:02 UTC, ramonski commented on src/senaite/impress/browser/viewlets/templates/content.pt
> +              i18n:domain="bika"
You are right, also the domain was wrong.
I removed it in https://github.com/senaite/senaite.impress/pull/133/commits/8fcbd51f0d75cd42d26ae9e93eaa0db18700494b

This template will be replaced with a content table of `senaite.app.listing` in the next PR.

2023-02-08 10:03 UTC, ramonski commented on src/senaite/impress/browser/configure.zcml
> +  <include package=".publish" />
This will be part of the next PR, sorry for that. Because I had the package already, it did not fail on my side.

2023-02-08 11:02 UTC, xispa approved these changes

2023-02-08 11:03 UTC, merged